web:
  build: .
  ports:
    - "8080:1337"
  volumes:
    - ./src/api:/src/api
    - ./src/config:/src/config
    - ./src/app.js:/src/app.js
  links:
    - mongodb:mongodb
  environment:
    MANDRILL_API_KEY: "BUFbKUNmFMA7PY6Pz4xcfw"
    APP_CONFIRMATION_URL: "http://docker:8080/confirm/"
    APP_RESET_URL: "http://docker:8080/reset/"
    MONGO_URL: mongodb://mongodb:27017/sails
    LOGGLY_SUBDOMAIN: murilopolese
    LOGGLY_TOKEN: f32b0847-e85e-4e11-a1c4-82b8828cb26d
    NEW_RELIC_APP_NAME: 'local'
    NEW_RELIC_KEY: '07794783d1400eef6222857287e1d51a7d7e9f63'
    NEW_RELIC_LEVEL: 'trace'
mongodb:
  image: mongo
  ports:
    - "27017:27017"
